import MySQLdb

conn = MySQLdb.connect(host="localhost",user="root",passwd="")
cursor = conn.cursor()
try:
    dbname = cursor.execute('CREATE DATABASE LBB')
except:
    pass
cursor.close()

food_info = """ CREATE TABLE `Food` (
  `id` varchar(300) COLLATE utf8_unicode_ci NOT NULL,
  `article_name` text COLLATE utf8_unicode_ci,
  `posted_by` text COLLATE utf8_unicode_ci,
  `city` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `state` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `article_description` mediumtext COLLATE utf8_unicode_ci NOT NULL, 
  `place_name` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `category` text COLLATE utf8_unicode_ci,
  `sub_category` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `working_hours` text COLLATE utf8_unicode_ci,
  `delivery_availablity` text COLLATE utf8_unicode_ci,
  `price` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `price_notes` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `contact_number` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `email` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `fb_link` text COLLATE utf8_unicode_ci,
  `web_link` text COLLATE utf8_unicode_ci,
  `twitter_link` text COLLATE utf8_unicode_ci,
  `instagram_link` text COLLATE utf8_unicode_ci,
  `nearest_railway_station` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `nearest_metro` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `location` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `street` varchar(10000) COLLATE utf8_unicode_ci NOT NULL,
  `address` text COLLATE utf8_unicode_ci,
  `place_image` text COLLATE utf8_unicode_ci,
  `place_url` text COLLATE utf8_unicode_ci,
  `reference_url` text COLLATE utf8_unicode_ci,
  `created_at` datetime NOT NULL,
  `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_seen` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci  """

lifestyle_info  = """ CREATE TABLE `Lifestyle`  (
  `id` varchar(300) COLLATE utf8_unicode_ci NOT NULL,
  `article_name` text COLLATE utf8_unicode_ci,
  `posted_by` text COLLATE utf8_unicode_ci,
  `city` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `state` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `article_description` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `place_name` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `category` text COLLATE utf8_unicode_ci,
  `sub_category` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `working_hours` text COLLATE utf8_unicode_ci,
  `delivery_availablity` text COLLATE utf8_unicode_ci,
  `price` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `price_notes` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `contact_number` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `email` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `fb_link` text COLLATE utf8_unicode_ci,
  `web_link` text COLLATE utf8_unicode_ci,
  `twitter_link` text COLLATE utf8_unicode_ci,
  `instagram_link` text COLLATE utf8_unicode_ci,
  `nearest_railway_station` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `nearest_metro` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `location` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `street` varchar(10000) COLLATE utf8_unicode_ci NOT NULL,
  `address` text COLLATE utf8_unicode_ci,
  `place_image` text COLLATE utf8_unicode_ci,
  `place_url` text COLLATE utf8_unicode_ci,
  `reference_url` text COLLATE utf8_unicode_ci,
  `created_at` datetime NOT NULL,
  `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_seen` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci """

culture_info  = """ CREATE TABLE `Culture` (
  `id` varchar(300) COLLATE utf8_unicode_ci NOT NULL,
  `article_name` text COLLATE utf8_unicode_ci,
  `posted_by` text COLLATE utf8_unicode_ci,
  `city` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `state` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `article_description` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `place_name` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `category` text COLLATE utf8_unicode_ci,
  `sub_category` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `working_hours` text COLLATE utf8_unicode_ci,
  `delivery_availablity` text COLLATE utf8_unicode_ci,
  `price` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `price_notes` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `contact_number` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `email` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `fb_link` text COLLATE utf8_unicode_ci,
  `web_link` text COLLATE utf8_unicode_ci,
  `twitter_link` text COLLATE utf8_unicode_ci,
  `instagram_link` text COLLATE utf8_unicode_ci,
  `nearest_railway_station` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `nearest_metro` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `location` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `street` varchar(10000) COLLATE utf8_unicode_ci NOT NULL,
  `address` text COLLATE utf8_unicode_ci,
  `place_image` text COLLATE utf8_unicode_ci,
  `place_url` text COLLATE utf8_unicode_ci,
  `reference_url` text COLLATE utf8_unicode_ci,
  `created_at` datetime NOT NULL,
  `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_seen` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci """

travel_info  = """ CREATE TABLE `Travel` (
  `id` varchar(300) COLLATE utf8_unicode_ci NOT NULL,
  `article_name` text COLLATE utf8_unicode_ci,
  `posted_by` text COLLATE utf8_unicode_ci,
  `city` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `state` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `article_description` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `place_name` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `category` text COLLATE utf8_unicode_ci,
  `sub_category` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `working_hours` text COLLATE utf8_unicode_ci,
  `delivery_availablity` text COLLATE utf8_unicode_ci,
  `price` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `price_notes` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `contact_number` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `email` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `fb_link` text COLLATE utf8_unicode_ci,
  `web_link` text COLLATE utf8_unicode_ci,
  `twitter_link` text COLLATE utf8_unicode_ci,
  `instagram_link` text COLLATE utf8_unicode_ci,
  `nearest_railway_station` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `nearest_metro` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `location` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `street` varchar(10000) COLLATE utf8_unicode_ci NOT NULL,
  `address` text COLLATE utf8_unicode_ci,
  `place_image` text COLLATE utf8_unicode_ci,
  `place_url` text COLLATE utf8_unicode_ci,
  `reference_url` text COLLATE utf8_unicode_ci,
  `created_at` datetime NOT NULL,
  `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_seen` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci """

shopping_info  = """ CREATE TABLE `Shopping` (
  `id` varchar(300) COLLATE utf8_unicode_ci NOT NULL,
  `article_name` text COLLATE utf8_unicode_ci,
  `posted_by` text COLLATE utf8_unicode_ci,
  `city` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `state` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `article_description` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `place_name` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `category` text COLLATE utf8_unicode_ci,
  `sub_category` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `working_hours` text COLLATE utf8_unicode_ci,
  `delivery_availablity` text COLLATE utf8_unicode_ci,
  `price` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `price_notes` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `contact_number` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `email` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `fb_link` text COLLATE utf8_unicode_ci,
  `web_link` text COLLATE utf8_unicode_ci,
  `twitter_link` text COLLATE utf8_unicode_ci,
  `instagram_link` text COLLATE utf8_unicode_ci,
  `nearest_railway_station` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `nearest_metro` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `location` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `street` varchar(10000) COLLATE utf8_unicode_ci NOT NULL,
  `address` text COLLATE utf8_unicode_ci,
  `place_image` text COLLATE utf8_unicode_ci,
  `place_url` text COLLATE utf8_unicode_ci,
  `reference_url` text COLLATE utf8_unicode_ci,
  `created_at` datetime NOT NULL,
  `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_seen` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci """

activity_info  = """ CREATE TABLE `Activity` (
  `id` varchar(300) COLLATE utf8_unicode_ci NOT NULL,
  `article_name` text COLLATE utf8_unicode_ci,
  `posted_by` text COLLATE utf8_unicode_ci,
  `city` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `state` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `article_description` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `place_name` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `category` text COLLATE utf8_unicode_ci,
  `sub_category` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `working_hours` text COLLATE utf8_unicode_ci,
  `delivery_availablity` text COLLATE utf8_unicode_ci,
  `price` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `price_notes` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `contact_number` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `email` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `fb_link` text COLLATE utf8_unicode_ci,
  `web_link` text COLLATE utf8_unicode_ci,
  `twitter_link` text COLLATE utf8_unicode_ci,
  `instagram_link` text COLLATE utf8_unicode_ci,
  `nearest_railway_station` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `nearest_metro` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `location` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `street` varchar(10000) COLLATE utf8_unicode_ci NOT NULL,
  `address` text COLLATE utf8_unicode_ci,
  `place_image` text COLLATE utf8_unicode_ci,
  `place_url` text COLLATE utf8_unicode_ci,
  `reference_url` text COLLATE utf8_unicode_ci,
  `created_at` datetime NOT NULL,
  `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_seen` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci """

fitenss_info  = """ CREATE TABLE `Fitness` (
  `id` varchar(300) COLLATE utf8_unicode_ci NOT NULL,
  `article_name` text COLLATE utf8_unicode_ci,
  `posted_by` text COLLATE utf8_unicode_ci,
  `city` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `state` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `article_description` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `place_name` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `category` text COLLATE utf8_unicode_ci,
  `sub_category` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `working_hours` text COLLATE utf8_unicode_ci,
  `delivery_availablity` text COLLATE utf8_unicode_ci,
  `price` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `price_notes` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `contact_number` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `email` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `fb_link` text COLLATE utf8_unicode_ci,
  `web_link` text COLLATE utf8_unicode_ci,
  `twitter_link` text COLLATE utf8_unicode_ci,
  `instagram_link` text COLLATE utf8_unicode_ci,
  `nearest_railway_station` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `nearest_metro` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `location` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `street` varchar(10000) COLLATE utf8_unicode_ci NOT NULL,
  `address` text COLLATE utf8_unicode_ci,
  `place_image` text COLLATE utf8_unicode_ci,
  `place_url` text COLLATE utf8_unicode_ci,
  `reference_url` text COLLATE utf8_unicode_ci,
  `created_at` datetime NOT NULL,
  `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_seen` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci """

events_info  = """ CREATE TABLE `Events` (
  `id` varchar(300) COLLATE utf8_unicode_ci NOT NULL,
  `article_name` text COLLATE utf8_unicode_ci,
  `posted_by` text COLLATE utf8_unicode_ci,
  `city` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `state` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `article_description` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `place_name` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `category` text COLLATE utf8_unicode_ci,
  `sub_category` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `working_hours` text COLLATE utf8_unicode_ci,
  `delivery_availablity` text COLLATE utf8_unicode_ci,
  `price` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `price_notes` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `contact_number` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `email` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `fb_link` text COLLATE utf8_unicode_ci,
  `web_link` text COLLATE utf8_unicode_ci,
  `twitter_link` text COLLATE utf8_unicode_ci,
  `instagram_link` text COLLATE utf8_unicode_ci,
  `nearest_railway_station` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `nearest_metro` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `location` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `street` varchar(10000) COLLATE utf8_unicode_ci NOT NULL,
  `address` text COLLATE utf8_unicode_ci,
  `place_image` text COLLATE utf8_unicode_ci,
  `place_url` text COLLATE utf8_unicode_ci,
  `reference_url` text COLLATE utf8_unicode_ci,
  `created_at` datetime NOT NULL,
  `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_seen` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci """

con = MySQLdb.connect(db   =  'LBB',
                      user              = 'root',
                      passwd            = '',
                      charset           = "utf8",
                      host              = 'localhost',
                      use_unicode       = True)
cur = con.cursor()

try:
    cur.execute(food_info)
    cur.execute(lifestyle_info)
    cur.execute(culture_info)
    cur.execute(travel_info)
    cur.execute(shopping_info)
    cur.execute(activity_info)
    cur.execute(fitenss_info)
    cur.execute(events_info)

except:
    pass

cur.close()
