listing_b = '//div[@class="row row-full"]//div//a//@href'
description_b = '//div[@class="content about"]/p/text()'
description_bb = '//div[@class="content about"]/text()'
name_b = '//div[@class="content-panel"]//div[@class="content panel-row last"]//h1//text()'
name_bb = '//div[@class="content panel-row"]//h1//text()'
image_urlb = '//div[@class="content-panel"]/img/@src'
latitude_b = '//div[@class="content-panel"]/div[@class="map-canvas map-pin"]/@data-lat'
longitude_b = '//div[@class="content-panel"]/div[@class="map-canvas map-pin"]/@data-lon'
address_b = '//div[@class="content-panel"]/div[@class="map-canvas map-pin"]/following-sibling::div[@class="content panel-row"]//text()'
contact_numbers_b = '//div[@class="content-panel"]/div[@class="content"]/following-sibling::div[@class="content panel-row"]/text()'
website_name_b = '//div[@class="content-panel"]/div[@class="content"]/following-sibling::div[@class="content panel-row"]/a/text()'
available_timings_b = '//div[@class="content-panel"]/div[@class="content panel-row last"]/p/i[@class="fa fa-clock-o"]/following-sibling::text()'
check_likes_b = '//i[contains(@class, "fa-thumbs-up")]/following-sibling::text()'
