listing_b = '//ul[@class="categories xsmall"]//li//a//@href'
listing3_b = '//div[@class="media product-summary mhn mtn light-border-b "]//div[@class="img product-image mrmm"]//a[@class="no-hover"]//@href'
next_b = '//h2[@class="man product-title"]//a//@href'
highlights_b = '//div[@class="cms-content"]//ul[@class="simple-list"]//li//text()'
expect_b = '//div[@class="line"]//div[@class="cms-content"]//text()'
description1_b = '//div[@id="tab1"]//div[@itemprop="description"]/text()'
description2_b = '//div[@id="tab1"]//div[@itemprop="description"]/div/text()'
except_imageb = '//div[@class="line"]//div[@class="unitRight mts mbm mlm"]//img//@src'
links_b = '//ul[@id="mainTabs"]//li[@class="mrs "]//@data-ref'
category_b = '//div[@class="crumbler"]/ul/li/a[@itemprop="item"]/span[@itemprop="name"]/text()'
name_b = '//h1//a//span[@itemprop="name"]//text()'
duration_b = '//li//span[@id="durationSpan"]//text()'
location_b = '//span[contains(text(), "Location:")]/following-sibling::text()'
tour_codeb = '//div[@class="xsmall main-title-bar-label mrs mhmm mvs"]//span//text()'
no_of_reviewsb = '//a//span[@itemprop="reviewCount"]//text()'
no_of_ratingsb = '//a//img[@class="unit mrs"]//@alt'
image_urlb = '//a[@class="img-link"]//@data-image-src'
inclusionsb = '//div[@class="mvm"]//div[contains(text(), "Inclusions")]/following-sibling::ul/li/text()'
exclusionsb = '//div[@class="mbm"]//div[contains(text(), "Exclusions")]/following-sibling::ul/li/text()'
additional_infob = '//div[@class="mbm"]//div[contains(text(), "Additional info")]/following-sibling::div/ul/li/text()'
voucher_infob = '//div[@class="mbm"]/div[contains(text(), "Voucher info")]/following-sibling::text()'
local_operator_infob = '//div[@class="mbm"]/div[contains(text(), "Local operator information")]/following-sibling::text()'
cancellation_policyb = '//div[@class="cms-content mtm"]/div[@class="mvm"]/text()'
departure_timeb = '//div[@class="mbm"]//div[contains(text(), "Departure time")]/following-sibling::text()'
return_detailsb = '//div[@class="mbm"]//span[contains(text(), "Return details")]/following-sibling::text()'
departure_pointb = '//div[@class="mbm"]//div[contains(text(), "Departure point")]/following-sibling::text()'
nodes_b = '//div[@class="light-border-t mbl"]//div[@class="line light-border-b option-row"]'
about_travelb = './/div[@class="unit size1of4"]/p[@class="mas"]/span[@class="strong"]//text()'
travel_code_b = './/div[@class="unit size1of4"]/p[@class="mas"]/span[@class="xsmall hint"]//text()'
travel_descriptionb = './/div[@class="unit size1of2"]//p[@class="mhs mvs"]//text()'
price_b = './/div[@class="txtR mas line"]//div[@class="h2 strong"]/span[@class="currency-sign"]/following-sibling::text()'
price_bb = '//span[@class="price-amount price-amount-l"]//span[@data-price-from]//text()'


