# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html


from scrapy.item import Item, Field

import scrapy


class MmtctItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    pass



class MMTRIPItem(Item):
    city =  Field()
    mmthotelname= Field()
    mmthotelid = Field()
    check_in = Field()
    dx = Field()
    los = Field()
    mmtpax = Field()
    mmtroomtype = Field()
    mmtrate = Field()
    mmtb2cdiff = Field()
    mmtinclusions = Field()
    mmtapprate = Field()
    mobilediff = Field()
    mmtb2csplashedprice = Field()
    mmtappsplashedprice = Field()
    mmtb2ctaxes = Field()
    mmtapptaxes = Field()
    child = Field()
    mmtcouponcode = Field()
    mmtcoupondescription = Field()
    mmtcoupondiscount  = Field()
    rmtc = Field()
    check_out = Field()
    gstincluded=Field()
    totalamtaftergst = Field()
    cancellation_policy = Field()
    ct_id = Field()
    unique_sk = Field()
    aux_info = Field()



class CTRIPItem(Item):
    city =  Field()
    cthotelname= Field()
    cthotelid = Field()
    check_in = Field()
    dx = Field()
    los = Field()
    ctpax = Field()
    ctroomtype = Field()
    ctrate = Field()
    ctb2cdiff = Field()
    ctinclusions = Field()
    ctapprate = Field()
    mobilediff = Field()
    ctb2csplashedprice = Field()
    ctappsplashedprice = Field()
    ctb2ctaxes = Field()
    ctapptaxes = Field()
    child = Field()
    ctcouponcode = Field()
    ctcoupondescription = Field()
    ctcoupondiscount  = Field()
    rmtc = Field()
    check_out = Field()
    ctsell_price = Field()
    ctchmm_discount = Field()
    cancellation_policy = Field()
    unique_sk = Field()
    aux_info = Field()



class GOBTRIPItem(Item):
    city =  Field()
    gbthotelname= Field()
    gbthotelid = Field()
    check_in = Field()
    dx = Field()
    los = Field()
    gbtpax = Field()
    gbtroomtype = Field()
    gbtrate = Field()
    gbtb2cdiff = Field()
    gbtinclusions = Field()
    gbtapprate = Field()
    mobilediff = Field()
    gbtb2csplashedprice = Field()
    gbtappsplashedprice = Field()
    gbtb2ctaxes = Field()
    gbtapptaxes = Field()
    child = Field()
    gbtcouponcode = Field()
    gbtcoupondescription = Field()
    gbtcoupondiscount  = Field()
    rmtc = Field()
    check_out = Field()
    gstincluded=Field()
    totalamtaftergst = Field()
    cancellation_policy = Field()
    ct_id = Field()
    unique_sk = Field()
    aux_info=Field()
    reference_url=Field()

class TRIPADVISORItem(Item):
    sk=Field()
    city_name=Field()
    property_name=Field()
    TA_hotel_id=Field()
    checkin=Field()
    DX=Field()
    Pax=Field()
    Ranking_Agoda=Field()
    Ranking_BookingCom=Field()
    Ranking_ClearTrip=Field()
    Ranking_Expedia=Field()
    Ranking_Goibibo=Field()
    Ranking_HotelsCom2=Field()
    Ranking_MakeMyTrip=Field()
    Ranking_Yatra=Field()
    Ranking_TG=Field()
    Price_Agoda=Field()
    Price_BookingCom=Field()
    Price_ClearTrip=Field()
    Price_Expedia=Field()
    Price_Goibibo=Field()
    Price_HotelsCom2=Field()
    Price_MakeMyTrip=Field()
    Price_Yatra=Field()
    Price_TG=Field()
    Tax_Agoda=Field()
    Tax_BookingCom=Field()
    Tax_ClearTrip=Field()
    Tax_Expedia=Field()
    Tax_Goibibo=Field()
    Tax_HotelsCom2=Field()
    Tax_MakeMyTrip=Field()
    Tax_Yatra=Field()
    Tax_TG=Field()
    Total_Agoda=Field()
    Total_BookingCom=Field()
    Total_ClearTrip=Field()
    Total_Expedia=Field()
    Total_Goibibo=Field()
    Total_HotelsCom2=Field()
    Total_MakeMyTrip=Field()
    Total_Yatra=Field()
    Total_TG=Field()
    Cheaper_Agoda=Field()
    Cheaper_BookingCom=Field()
    Cheaper_ClearTrip=Field()
    Cheaper_Expedia=Field()
    Cheaper_Goibibo=Field()
    Cheaper_HotelsCom2=Field()
    Cheaper_MakeMyTrip=Field()
    Cheaper_Yatra=Field()
    Cheaper_TG=Field()
    Status_Agoda=Field()
    Status_BookingCom=Field()
    Status_ClearTrip=Field()
    Status_Expedia=Field()
    Status_Goibibo=Field()
    Status_HotelsCom2=Field()
    Status_MakeMyTrip=Field()
    Status_Yatra=Field()
    Status_TG=Field()
    Ranking_Stayzilla=Field()
    Price_Stayzilla=Field()
    Tax_Stayzilla=Field()
    Total_Stayzilla=Field()
    Cheaper_Stayzilla=Field()
    Status_Stayzilla=Field()
    Time=Field()
    reference_url=Field()
class TRIPADVISORcityrankItem(Item):
    sk=Field()
    city_rank=Field()

class TRIVAGOItem(Item):
     sk=Field()
     crawl_table_sk=Field()
     city=Field()
     cleartrip_hotel_id=Field()
     hotel_name=Field()
     trivago_hotel_id=Field()
     check_in=Field()
     los=Field()
     rank1=Field()
     rank2=Field()
     rank3=Field()
     rank4=Field()
     ct_price=Field()
     ct_type=Field()
     expedia_price=Field()
     expedia_type=Field()
     hotelsdot_com_price=Field()
     hotelsdot_com_type=Field()
     bookingdot_com_price=Field()
     bookingdot_com_type=Field()
     hotel_info_price=Field()
     hotel_info_type=Field()
     mmt_price=Field()
     mmt_type=Field()
     agoda_price=Field()
     agoda_type=Field()
     amoma_price=Field()
     amoma_type=Field()
     hrs_price=Field()
     hrs_type=Field()
     available_otas=Field()
     price_difference=Field()
     beaten_by_booking_com=Field()
     beaten_by_price=Field()
     aux_info=Field()
     check_out=Field()
     reference_url=Field()

class BookingItem(Item):
     pax = Field()
     child = Field()
     dx = Field()
     los = Field()
     check_in = Field()
     check_out = Field()
     city = Field()
     hotelname = Field()
     hotelid = Field()
     room_type = Field()
     rmtc = Field()
     rate_plan = Field()
     final_rate_plan = Field()
     inclusions = Field()
     cancellation_policy = Field()
     splashed_price = Field()
     actual_price = Field()
     gst_amt = Field()
     ct_id = Field()
     unique_sk = Field()
     aux_info = Field()
     reference_url = Field()

class TripadvisorInventoryItem(Item):
    sk=Field()
    city_name=Field()
    property_name=Field()
    TA_hotel_id=Field()
    CT_hotel_id=Field()
    checkin=Field()
    DX=Field()
    Pax=Field()
    ct_price=Field()
    cheapest_ota_price=Field()
    cheapest_ota_name=Field()
    ct_room_name=Field()
    cheapest_ota_room_name=Field()
    status=Field()
    which_case=Field()
    Ranking_ClearTrip=Field()
    Time=Field()
    reference_url=Field()
    from_ta_url=Field()
    main_url=Field()
